from uuid import UUID, uuid4

from pydantic import BaseModel, Field


class UUIDMixin(BaseModel):
    """
    A Pydantic mixin model that provides a UUID field.

    :param uuid: The universally unique identifier (UUID) for an object, default is generated by uuid4.
    """
    uuid: UUID = Field(default_factory=uuid4)
