# Generated by Django 4.2.2 on 2023-07-20 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_genrefilmwork_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='personfilmwork',
            unique_together={('person', 'film_work', 'role')},
        ),
    ]
