"""change table sessions

Revision ID: 04ce3f845f6a
Revises: e9c61e162c9a
Create Date: 2023-11-28 07:09:33.947974

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '04ce3f845f6a'
down_revision: Union[str, None] = 'e9c61e162c9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('refresh_token', sa.Text(), nullable=True), schema='content')
    op.create_unique_constraint('uix_user_id_user_agent', 'sessions', ['user_id', 'user_agent'], schema='content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_user_id_user_agent', 'sessions', schema='content', type_='unique')
    op.drop_column('sessions', 'refresh_token', schema='content')
    # ### end Alembic commands ###
