"""Migration to change index name

Revision ID: 3c347ae0530e
Revises: 85b00079b88c
Create Date: 2023-11-29 11:47:36.624153

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3c347ae0530e'
down_revision: Union[str, None] = '85b00079b88c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_tokens',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('user_id', sa.UUID(), nullable=True),
                    sa.Column('jwt_token', sa.Text(), nullable=True),
                    sa.Column('user_agent', sa.String(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('expiry_date', sa.DateTime(), nullable=True),
                    sa.Column('is_valid', sa.Boolean(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['content.users.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    schema='content'
                    )
    op.create_index('idx_refresh_tokens_token', 'refresh_tokens', ['jwt_token', 'user_agent'], unique=False,
                    schema='content')
    op.create_index(op.f('ix_content_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False, schema='content')
    op.create_index(op.f('ix_content_refresh_tokens_jwt_token'), 'refresh_tokens', ['jwt_token'], unique=False,
                    schema='content')
    op.drop_index('idx_user_id_expiry_date', table_name='unauthorized_refresh_tokens', schema='content')
    op.drop_index('ix_content_unauthorized_refresh_tokens_id', table_name='unauthorized_refresh_tokens',
                  schema='content')
    op.drop_index('ix_content_unauthorized_refresh_tokens_jwt_token', table_name='unauthorized_refresh_tokens',
                  schema='content')
    op.drop_table('unauthorized_refresh_tokens', schema='content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unauthorized_refresh_tokens',
                    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
                    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
                    sa.Column('jwt_token', sa.TEXT(), autoincrement=False, nullable=True),
                    sa.Column('user_agent', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
                    sa.Column('expiry_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
                    sa.Column('is_valid', sa.BOOLEAN(), autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['content.users.id'],
                                            name='unauthorized_refresh_tokens_user_id_fkey'),
                    sa.PrimaryKeyConstraint('id', name='unauthorized_refresh_tokens_pkey'),
                    schema='content'
                    )
    op.create_index('ix_content_unauthorized_refresh_tokens_jwt_token', 'unauthorized_refresh_tokens', ['jwt_token'],
                    unique=False, schema='content')
    op.create_index('ix_content_unauthorized_refresh_tokens_id', 'unauthorized_refresh_tokens', ['id'], unique=False,
                    schema='content')
    op.create_index('idx_user_id_expiry_date', 'unauthorized_refresh_tokens', ['user_id', 'expiry_date'], unique=False,
                    schema='content')
    op.drop_index(op.f('ix_content_refresh_tokens_jwt_token'), table_name='refresh_tokens', schema='content')
    op.drop_index(op.f('ix_content_refresh_tokens_id'), table_name='refresh_tokens', schema='content')
    op.drop_index('idx_refresh_tokens_token', table_name='refresh_tokens', schema='content')
    op.drop_table('refresh_tokens', schema='content')
    # ### end Alembic commands ###
