"""Added role description column

Revision ID: 7312d2679153
Revises: 9cbd6d66dbc6
Create Date: 2023-12-05 14:22:34.782893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7312d2679153'
down_revision: Union[str, None] = '9cbd6d66dbc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('description', sa.Text(), nullable=True), schema='content')
    op.alter_column('roles', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='content')
    op.drop_constraint('roles_name_key', 'roles', schema='content', type_='unique')
    op.drop_index('ix_content_roles_id', table_name='roles', schema='content')
    op.create_index(op.f('ix_content_roles_id'), 'roles', ['id'], unique=True, schema='content')
    op.create_index(op.f('ix_content_roles_name'), 'roles', ['name'], unique=True, schema='content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_content_roles_name'), table_name='roles', schema='content')
    op.drop_index(op.f('ix_content_roles_id'), table_name='roles', schema='content')
    op.create_index('ix_content_roles_id', 'roles', ['id'], unique=False, schema='content')
    op.create_unique_constraint('roles_name_key', 'roles', ['name'], schema='content')
    op.alter_column('roles', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='content')
    op.drop_column('roles', 'description', schema='content')
    # ### end Alembic commands ###
