"""Remove session

Revision ID: 85b00079b88c
Revises: 04ce3f845f6a
Create Date: 2023-11-29 11:33:00.214646

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '85b00079b88c'
down_revision: Union[str, None] = '04ce3f845f6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessions', schema='content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
                    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
                    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
                    sa.Column('user_agent', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('ip_address', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('refresh_token', sa.TEXT(), autoincrement=False, nullable=True),
                    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
                    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['content.users.id'], name='sessions_user_id_fkey'),
                    sa.PrimaryKeyConstraint('id', name='sessions_pkey'),
                    sa.UniqueConstraint('user_id', 'user_agent', name='uix_user_id_user_agent'),
                    schema='content'
                    )
    # ### end Alembic commands ###
