"""added session table and user_agent field

Revision ID: e9c61e162c9a
Revises: e34f0a54e87c
Create Date: 2023-11-26 20:59:52.528670

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e9c61e162c9a'
down_revision: Union[str, None] = 'e34f0a54e87c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('user_id', sa.UUID(), nullable=True),
                    sa.Column('user_agent', sa.String(), nullable=True),
                    sa.Column('ip_address', sa.String(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['content.users.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    schema='content'
                    )
    op.add_column('unauthorized_refresh_tokens', sa.Column('user_agent', sa.String(), nullable=True), schema='content')
    op.create_index('idx_user_id_expiry_date', 'unauthorized_refresh_tokens', ['user_id', 'expiry_date'], unique=False,
                    schema='content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_id_expiry_date', table_name='unauthorized_refresh_tokens', schema='content')
    op.drop_column('unauthorized_refresh_tokens', 'user_agent', schema='content')
    op.drop_table('sessions', schema='content')
    # ### end Alembic commands ###
